### ISSUE TITLE
uLux readings

### ISSUE THREAD

**Issue by jalbarra** [jremington/TSL2591#1]
Hi,
Is it possible with your code to get readings from uLux? I need to make measurements of very low light intensity and, despite the fact that this sensor seems to measure up to 18 uLux, I have not achieved a resolution lower than 1 Lux. I have searched a lot but the solution does not seem easy. Thanks !

**Comment by jremington** [comment]
The code supplies the RAW readings from the photodiodes.  Lux levels are an approximation for how the human eye sees, and are estimated from the raw readings by a calculation that is documented elsewhere. In my opinion lux levels are not meaningful for low light intensities as the human eye sees black and white only, with a different spectral sensitivity response than color vision.

If you want the lux readings, use the TSL2591MI library linked in the README, which has that calculation built in.

**Comment by jalbarra** [comment]
I don't really need an accurate reading in Lux, I want to use this sensor to detect human presence in caves, and therefore I only need to record small variations in very low light levels, on the order of micro Lux. It would also help me to have a raw reading from the sensor, if it really registered changes in intensity close to absolute darkness
Thanks,
